# Generated by Django 5.0.1 on 2024-05-09 18:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stockable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=32, verbose_name='Модель')),
                ('size', models.CharField(max_length=7, verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'модель',
                'verbose_name_plural': 'модели',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=2024, verbose_name='Год')),
                ('month', models.PositiveSmallIntegerField(default=5, verbose_name='Месяц')),
            ],
            options={
                'verbose_name': 'таблица',
                'verbose_name_plural': 'таблицы',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('A', 'Добавить в систему'), ('O', 'Пометить как бронь'), ('C', 'Отменить бронь'), ('S', 'Отметить как проданный'), ('R', 'Получить возврат'), ('T', 'Переместить')], default='A', max_length=1, verbose_name='Тип действия')),
                ('person', models.CharField(max_length=2, verbose_name='Деятель')),
                ('place', models.CharField(choices=[('CA', 'Машина'), ('SN', 'Главный склад'), ('SO', 'Склад 2'), ('JU', 'Джамбо'), ('CI', 'Чеканы'), ('RI', 'Рышкановка'), ('D1', 'Игорь'), ('D2', 'Оргеев'), ('D3', 'Унгены')], max_length=2, verbose_name='Место товара')),
                ('date', models.DateField(default=datetime.datetime.today, verbose_name='Дата')),
                ('stockable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='stock.stockable', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'действие',
                'verbose_name_plural': 'действия',
            },
        ),
        migrations.AddField(
            model_name='stockable',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockables', to='stock.table'),
        ),
    ]
