# Generated by Django 5.0.1 on 2024-05-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_stockable_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockable',
            options={'ordering': ['product', 'size'], 'verbose_name': 'модель', 'verbose_name_plural': 'модели'},
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.CharField(choices=[('H', 'В ожидании действия'), ('A', 'Добавить в систему'), ('O', 'Пометить как бронь'), ('C', 'Отменить бронь'), ('S', 'Отметить как проданный'), ('R', 'Получить возврат'), ('T', 'Переместить')], default='A', max_length=1, verbose_name='Тип действия'),
        ),
    ]
