# Generated by Django 5.0.1 on 2024-05-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_stockable_options_alter_action_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockable',
            options={'ordering': ['category', 'product', 'size'], 'verbose_name': 'модель', 'verbose_name_plural': 'модели'},
        ),
        migrations.AddField(
            model_name='stockable',
            name='category',
            field=models.CharField(choices=[('MA', 'Матрас'), ('PI', 'Подушка'), ('MP', 'Наматрасник'), ('BE', 'Кровать')], default='MA', max_length=2, verbose_name='Категория'),
        ),
    ]
