# Generated by Django 5.0.1 on 2024-05-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_stockable_options_stockable_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockable',
            name='category',
            field=models.CharField(choices=[('MSP', 'Матрас Special'), ('MSM', 'Матрас Smart'), ('MAL', 'Матрас Alba'), ('MVK', 'Матрас Vegas Kids'), ('MAC', 'Матрас Active'), ('MEC', 'Матрас Ecolatex'), ('MEX', 'Матрас Exclusive'), ('MMO', 'Матрас Modern'), ('MCO', 'Матрас Comfort'), ('PI', 'Подушка'), ('MPP', 'Наматрасник Protect'), ('MPT', 'Наматрасник Transform'), ('BE', 'Кровать')], max_length=3, verbose_name='Категория'),
        ),
    ]
