# Generated by Django 5.0.1 on 2024-05-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_stockable_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.CharField(choices=[('H', 'В ожидании действия'), ('A', 'Добавить в систему'), ('O', 'Пометить как бронь'), ('C', 'Отменить бронь'), ('S', 'Отметить как проданный'), ('R', 'Получить возврат'), ('T', 'Переместить')], default='A', max_length=6, verbose_name='Тип действия'),
        ),
    ]
