# Generated by Django 5.0.1 on 2024-05-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='place',
            field=models.CharField(choices=[('Машина', 'Машина'), ('S1', 'Главный склад'), ('S2', 'Склад 2'), ('J', 'Джамбо'), ('C', 'Чеканы'), ('R', 'Рышкановка'), ('D1', 'Игорь'), ('D2', 'Оргеев'), ('D3', 'Унгены')], max_length=6, verbose_name='Место товара'),
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.CharField(choices=[('H', 'В ожидании действия'), ('A', 'Добавить в систему'), ('O', 'Пометить как бронь'), ('C', 'Отменить бронь'), ('S', 'Отметить как проданный'), ('R', 'Получить возврат'), ('T', 'Переместить')], default='A', max_length=1, verbose_name='Тип действия'),
        ),
    ]
