# Generated by Django 5.0.1 on 2024-05-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_alter_action_place_alter_action_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockable',
            options={'ordering': ['category', 'product'], 'verbose_name': 'модель', 'verbose_name_plural': 'модели'},
        ),
        migrations.AddField(
            model_name='stockable',
            name='length',
            field=models.SmallIntegerField(default=0, verbose_name='Длина'),
        ),
        migrations.AddField(
            model_name='stockable',
            name='width',
            field=models.SmallIntegerField(default=0, verbose_name='Ширина'),
        ),
    ]
