# Generated by Django 5.0.1 on 2024-05-19 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_alter_stockable_options_stockable_length_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockable',
            options={'ordering': ['category', 'product', 'width', 'length'], 'verbose_name': 'модель', 'verbose_name_plural': 'модели'},
        ),
        migrations.RemoveField(
            model_name='stockable',
            name='size',
        ),
    ]
