# Generated by Django 5.0.1 on 2024-06-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_alter_stockable_options_remove_stockable_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockable',
            name='category',
            field=models.CharField(choices=[('MSP', 'Матрасы Special'), ('MSM', 'Матрасы Smart'), ('MAL', 'Матрасы Alba'), ('MVK', 'Матрасы Vegas Kids'), ('MAC', 'Матрасы Active'), ('MEC', 'Матрасы Ecolatex'), ('MEX', 'Матрасы Exclusive'), ('MMO', 'Матрасы Modern'), ('MCO', 'Матрасы Comfort'), ('PI', 'Подушки'), ('MPP', 'Наматрасники Protect'), ('MPT', 'Наматрасники Transform'), ('BL', 'Одеяла'), ('BE', 'Кровати')], max_length=3, verbose_name='Категория'),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('year', 'month')},
        ),
    ]
