# Generated by Django 5.0.1 on 2024-07-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_alter_stockable_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='month',
            field=models.PositiveSmallIntegerField(default=8, verbose_name='Месяц'),
        ),
    ]
