# Generated by Django 4.0.5 on 2022-06-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('api', '0003_stand_pillow_mattresspads_mattrass_blanket_bedsheets_and_more'),
  ]

  operations = [
    migrations.AlterField(
      model_name='basis',
      name='id',
      field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
    ),
    migrations.AlterField(
      model_name='bed',
      name='id',
      field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
    ),
    migrations.AlterField(
      model_name='bedsheets',
      name='id',
      field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
    ),
    migrations.AlterField(
      model_name='blanket',
      name='id',
      field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
    ),
    migrations.AlterField(
      model_name='mattrass',
      name='id',
      field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
    ),
    migrations.AlterField(
      model_name='mattresspads',
      name='id',
      field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
    ),
    migrations.AlterField(
      model_name='pillow',
      name='id',
      field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
    ),
    migrations.AlterField(
      model_name='stand',
      name='id',
      field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
    ),
  ]
