# Generated by Django 4.0.5 on 2022-06-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('api', '0005_basis_best_bed_best_bedsheets_best_blanket_best_and_more'),
  ]

  operations = [
    migrations.RemoveField(
      model_name='basis',
      name='country',
    ),
    migrations.RemoveField(
      model_name='bed',
      name='country',
    ),
    migrations.RemoveField(
      model_name='bedsheets',
      name='country',
    ),
    migrations.RemoveField(
      model_name='blanket',
      name='country',
    ),
    migrations.RemoveField(
      model_name='mattrass',
      name='country',
    ),
    migrations.RemoveField(
      model_name='mattresspads',
      name='country',
    ),
    migrations.RemoveField(
      model_name='pillow',
      name='country',
    ),
    migrations.RemoveField(
      model_name='stand',
      name='country',
    ),
    migrations.AlterField(
      model_name='choice',
      name='name',
      field=models.CharField(choices=[('ОБЩИЕ', 'ОБЩИЕ'), ('Для возраста', 'Для возраста'), ('Упаковка', 'Упаковка'), ('Ткань чехла', 'Ткань чехла'), ('Материал обивки', 'Материал обивки'), ('', ''), ('Матрас', 'ТОЛЬКО МАТРАСЫ'), ('Коллекция', 'Коллекция'), ('Конструкция', 'Конструкция'), ('Уровень жесткости стороны 1', 'Уровень жесткости стороны 1'), ('Уровень жесткости стороны 2', 'Уровень жесткости стороны 2'), ('Пружинный блок', 'Пружинный блок'), ('Тип матраса', 'Тип матраса'), ('', ''), ('Подушка', 'ТОЛЬКО ПОДУШКИ'), ('Материал наполнения', 'Материал наполнения'), ('', ''), ('Наматрасник', 'ТОЛЬКО НАМАТРАСНИКИ'), ('Тип наматрасника', 'Тип наматрасника'), ('Крепление', 'Крепление'), ('', ''), ('Одеяло', 'ТОЛЬКО ОДЕЯЛА'), ('Цвет одеяла', 'Цвет одеяла'), ('Тип одеяла', 'Тип одеяла'), ('Наполнитель', 'Наполнитель'), ('', ''), ('Белье', 'ТОЛЬКОПОСТЕЛЬНОЕ БЕЛЬЕ'), ('Тип комплекта', 'Тип комплекта'), ('Цвет комплекта', 'Цвет комплекта'), ('', ''), ('Кровати', 'ТОЛЬКО КРОВАТИ'), ('Вид кровати', 'Вид кровати'), ('Порода древесины', 'Порода древесины')], max_length=32, verbose_name='Характеристика'),
    ),
  ]
