# Generated by Django 4.0.5 on 2022-07-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_basis_country_remove_bed_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.SmallIntegerField(verbose_name='Ширина')),
                ('length', models.SmallIntegerField(verbose_name='Длина')),
                ('priceEUR', models.SmallIntegerField(verbose_name='Цена (евро)')),
                ('priceMDL', models.SmallIntegerField(verbose_name='Цена (леи)')),
            ],
        ),
        migrations.RemoveField(
            model_name='bed',
            name='length',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='width',
        ),
        migrations.AlterField(
            model_name='mattrass',
            name='springs',
            field=models.IntegerField(default=0, verbose_name='Кол-во пружин в двуспальном матрасе'),
        ),
        migrations.AddField(
            model_name='basis',
            name='sizes',
            field=models.ManyToManyField(related_name='sizesBa', to='api.size', verbose_name='Размеры'),
        ),
        migrations.AddField(
            model_name='bed',
            name='sizes',
            field=models.ManyToManyField(related_name='sizesB', to='api.size', verbose_name='Размеры'),
        ),
        migrations.AddField(
            model_name='bedsheets',
            name='sizes',
            field=models.ManyToManyField(related_name='sizesBS', to='api.size', verbose_name='Размеры'),
        ),
        migrations.AddField(
            model_name='blanket',
            name='sizes',
            field=models.ManyToManyField(related_name='sizesBl', to='api.size', verbose_name='Размеры'),
        ),
        migrations.AddField(
            model_name='mattrass',
            name='sizes',
            field=models.ManyToManyField(related_name='sizesM', to='api.size', verbose_name='Размеры'),
        ),
        migrations.AddField(
            model_name='mattresspads',
            name='sizes',
            field=models.ManyToManyField(related_name='sizesMP', to='api.size', verbose_name='Размеры'),
        ),
    ]
