# Generated by Django 4.0.5 on 2022-07-02 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

  dependencies = [
    ('api', '0007_size_remove_bed_length_remove_bed_width_and_more'),
  ]

  operations = [
    migrations.AlterModelOptions(
      name='bed',
      options={'verbose_name': 'кровать', 'verbose_name_plural': 'кровати'},
    ),
    migrations.AlterModelOptions(
      name='size',
      options={'verbose_name': 'размер', 'verbose_name_plural': 'размеры'},
    ),
    migrations.RemoveField(
      model_name='basis',
      name='garanty',
    ),
    migrations.RemoveField(
      model_name='bed',
      name='basis_included',
    ),
    migrations.RemoveField(
      model_name='bed',
      name='garanty',
    ),
    migrations.RemoveField(
      model_name='bed',
      name='lifetime',
    ),
    migrations.RemoveField(
      model_name='bed',
      name='material',
    ),
    migrations.RemoveField(
      model_name='bed',
      name='mattrass_included',
    ),
    migrations.RemoveField(
      model_name='bed',
      name='wood',
    ),
    migrations.RemoveField(
      model_name='blanket',
      name='tissue',
    ),
    migrations.RemoveField(
      model_name='mattrass',
      name='garanty',
    ),
    migrations.RemoveField(
      model_name='mattresspads',
      name='garanty',
    ),
    migrations.RemoveField(
      model_name='pillow',
      name='garanty',
    ),
    migrations.RemoveField(
      model_name='pillow',
      name='package',
    ),
    migrations.RemoveField(
      model_name='stand',
      name='garanty',
    ),
    migrations.AddField(
      model_name='basis',
      name='height',
      field=models.IntegerField(null=True, verbose_name='Высота'),
    ),
    migrations.AddField(
      model_name='basis',
      name='legs_height',
      field=models.IntegerField(null=True, verbose_name='Высота ножек'),
    ),
    migrations.AddField(
      model_name='basis',
      name='type',
      field=models.ManyToManyField(related_name='typeBa', to='api.choice', verbose_name='Вид основания'),
    ),
    migrations.AlterField(
      model_name='bedsheets',
      name='material',
      field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materialBS', to='api.choice', verbose_name='Материал'),
    ),
    migrations.AlterField(
      model_name='mattrass',
      name='height',
      field=models.IntegerField(null=True, verbose_name='Высота'),
    ),
    migrations.AlterField(
      model_name='mattresspads',
      name='height',
      field=models.IntegerField(null=True, verbose_name='Высота'),
    ),
    migrations.AlterField(
      model_name='stand',
      name='height',
      field=models.IntegerField(null=True, verbose_name='Высота'),
    ),
    migrations.AlterField(
      model_name='stand',
      name='material',
      field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materialS', to='api.choice', verbose_name='Материал'),
    ),
  ]
