# Generated by Django 4.0.5 on 2022-07-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('api', '0008_alter_bed_options_alter_size_options_and_more'),
  ]

  operations = [
    migrations.RenameModel(
      old_name='MattressPads',
      new_name='MattrassPad',
    ),
    migrations.AlterModelOptions(
      name='category',
      options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
    ),
    migrations.AlterField(
      model_name='category',
      name='name',
      field=models.CharField(choices=[('Mattrass', 'Матрас'), ('Pillow', 'Подушка'), ('MattrassPad', 'Наматрасник'), ('Blanket', 'Одеяло'), ('BedSheets', 'Постельное белье'), ('Bed', 'Кровать'), ('Stand', 'Тумба'), ('Basis', 'Основание')], max_length=32, unique=True, verbose_name='Название'),
    ),
    migrations.AlterField(
      model_name='choice',
      name='name',
      field=models.CharField(choices=[('ОБЩИЕ', 'ОБЩИЕ'), ('Для возраста', 'Для возраста'), ('Упаковка', 'Упаковка'), ('Материал', 'Материал'), ('Ткань чехла', 'Ткань чехла'), ('', ''), ('Mattrass', 'ТОЛЬКО МАТРАСЫ'), ('Тип матраса', 'Тип матраса'), ('Коллекция', 'Коллекция'), ('Конструкция', 'Конструкция'), ('Уровень жесткости стороны 1', 'Уровень жесткости стороны 1'), ('Уровень жесткости стороны 2', 'Уровень жесткости стороны 2'), ('Пружинный блок', 'Пружинный блок'), ('', ''), ('Pillow', 'ТОЛЬКО ПОДУШКИ'), ('Материал наполнения', 'Материал наполнения'), ('', ''), ('MattrassPad', 'ТОЛЬКО НАМАТРАСНИКИ'), ('Тип наматрасника', 'Тип наматрасника'), ('Крепление', 'Крепление'), ('', ''), ('Blanket', 'ТОЛЬКО ОДЕЯЛА'), ('Тип одеяла', 'Тип одеяла'), ('Цвет одеяла', 'Цвет одеяла'), ('Наполнитель', 'Наполнитель'), ('', ''), ('BedSheets', 'ТОЛЬКО ПОСТЕЛЬНОЕ БЕЛЬЕ'), ('Тип комплекта', 'Тип комплекта'), ('Цвет комплекта', 'Цвет комплекта'), ('', ''), ('Bed', 'ТОЛЬКО КРОВАТИ'), ('Вид кровати', 'Вид кровати')], max_length=32, verbose_name='Характеристика'),
    ),
  ]
