# Generated by Django 4.0.5 on 2022-07-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_mattresspads_mattrasspad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='property',
            new_name='property_ru',
        ),
        migrations.AddField(
            model_name='choice',
            name='property_ro',
            field=models.CharField(blank=True, max_length=32, verbose_name='Вариант выбора'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='name',
            field=models.CharField(choices=[('ОБЩИЕ', 'ОБЩИЕ'), ('age', 'Д'), ('package', 'У'), ('cover', 'Т'), ('', ''), ('Mattrass', 'ТОЛЬКО М'), ('mattrass_type', 'Т'), ('collection', 'К'), ('construction', 'К'), ('rigidity1', 'У'), ('rigidity2', 'У'), ('springblock', 'П'), ('', ''), ('Pillow', 'ТОЛЬКО П'), ('material_filler', 'М'), ('', ''), ('MattrassPad', 'ТОЛЬКО Н'), ('mattrasspad_type', 'Т'), ('binding', 'К'), ('', ''), ('Blanket', 'ТОЛЬКО О'), ('blanket_type', 'Т'), ('blanket_color', 'Ц'), ('filling', 'Н'), ('', ''), ('BedSheets', 'ТОЛЬКО П'), ('bedsheets_type', 'Т'), ('bedsheets_color', 'Ц'), ('tissue', 'Т'), ('', ''), ('Bed', 'ТОЛЬКО К'), ('bed_type', 'В'), ('', ''), ('Stand', 'ТОЛЬКО Т'), ('material', 'М'), ('', ''), ('Basis', 'ТОЛЬКО О'), ('basis_type', 'В')], max_length=32, verbose_name='Характеристика'),
        ),
    ]
