# Generated by Django 4.0.5 on 2022-07-05 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_choice_property_ro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basis',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bed',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bedsheets',
            options={},
        ),
        migrations.AlterModelOptions(
            name='blanket',
            options={},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='mattrasspad',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pillow',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stand',
            options={},
        ),
        migrations.RemoveField(
            model_name='basis',
            name='type',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='type',
        ),
        migrations.RemoveField(
            model_name='bedsheets',
            name='color',
        ),
        migrations.RemoveField(
            model_name='bedsheets',
            name='material',
        ),
        migrations.RemoveField(
            model_name='bedsheets',
            name='type',
        ),
        migrations.RemoveField(
            model_name='blanket',
            name='color',
        ),
        migrations.RemoveField(
            model_name='blanket',
            name='type',
        ),
        migrations.RemoveField(
            model_name='mattrass',
            name='type',
        ),
        migrations.RemoveField(
            model_name='mattrasspad',
            name='tissue',
        ),
        migrations.RemoveField(
            model_name='mattrasspad',
            name='type',
        ),
        migrations.RemoveField(
            model_name='pillow',
            name='material',
        ),
        migrations.RemoveField(
            model_name='pillow',
            name='tissue',
        ),
        migrations.AddField(
            model_name='basis',
            name='basis_type',
            field=models.ManyToManyField(related_name='basis_type', to='api.choice', verbose_name='Вид основания'),
        ),
        migrations.AddField(
            model_name='bed',
            name='bed_type',
            field=models.ManyToManyField(related_name='bed_type', to='api.choice', verbose_name='Вид кровати'),
        ),
        migrations.AddField(
            model_name='bedsheets',
            name='bedsheets_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bedsheets_color', to='api.choice', verbose_name='Цвет комплекта'),
        ),
        migrations.AddField(
            model_name='bedsheets',
            name='bedsheets_type',
            field=models.ManyToManyField(related_name='bedsheets_type', to='api.choice', verbose_name='Тип комплекта'),
        ),
        migrations.AddField(
            model_name='bedsheets',
            name='tissue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tissue', to='api.choice', verbose_name='Ткань'),
        ),
        migrations.AddField(
            model_name='blanket',
            name='blanket_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blanket_color', to='api.choice', verbose_name='Цвет одеяла'),
        ),
        migrations.AddField(
            model_name='blanket',
            name='blanket_type',
            field=models.ManyToManyField(related_name='blanket_type', to='api.choice', verbose_name='Тип одеяла'),
        ),
        migrations.AddField(
            model_name='mattrass',
            name='mattras_type',
            field=models.ManyToManyField(related_name='mattrass_type', to='api.choice', verbose_name='Тип матраса'),
        ),
        migrations.AddField(
            model_name='mattrasspad',
            name='mattrasspad_type',
            field=models.ManyToManyField(related_name='mattrasspad_type', to='api.choice', verbose_name='Тип наматрасника'),
        ),
        migrations.AddField(
            model_name='pillow',
            name='material_filler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_filler', to='api.choice', verbose_name='Материал наполнения'),
        ),
        migrations.AlterField(
            model_name='bedsheets',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packageBS', to='api.choice', verbose_name='Упаковка'),
        ),
        migrations.AlterField(
            model_name='blanket',
            name='filling',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filling', to='api.choice', verbose_name='Наполнитель'),
        ),
        migrations.AlterField(
            model_name='blanket',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packageBl', to='api.choice', verbose_name='Упаковка'),
        ),
        migrations.AlterField(
            model_name='mattrass',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='api.choice', verbose_name='Коллекция'),
        ),
        migrations.AlterField(
            model_name='mattrass',
            name='construction',
            field=models.ManyToManyField(related_name='construction', to='api.choice', verbose_name='Конструкция'),
        ),
        migrations.AlterField(
            model_name='mattrass',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packageM', to='api.choice', verbose_name='Упаковка'),
        ),
        migrations.AlterField(
            model_name='mattrass',
            name='rigidity1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rigidity1', to='api.choice', verbose_name='Уровень жесткости стороны 1'),
        ),
        migrations.AlterField(
            model_name='mattrass',
            name='rigidity2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rigidity2', to='api.choice', verbose_name='Уровень жесткости стороны 2'),
        ),
        migrations.AlterField(
            model_name='mattrass',
            name='springblock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='springblock', to='api.choice', verbose_name='Пружинный блок'),
        ),
        migrations.AlterField(
            model_name='mattrasspad',
            name='binding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='binding', to='api.choice', verbose_name='Крепление'),
        ),
        migrations.RemoveField(
            model_name='mattrasspad',
            name='cover',
        ),
        migrations.AddField(
            model_name='mattrasspad',
            name='cover',
            field=models.ManyToManyField(related_name='coverMP', to='api.choice', verbose_name='Ткань чехла'),
        ),
        migrations.RemoveField(
            model_name='pillow',
            name='cover',
        ),
        migrations.AddField(
            model_name='pillow',
            name='cover',
            field=models.ManyToManyField(related_name='coverP', to='api.choice', verbose_name='Ткань чехла'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material', to='api.choice', verbose_name='Материал'),
        ),
    ]
