# Generated by Django 4.0.5 on 2022-07-07 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

  dependencies = [
    ('api', '0015_alter_bedsheets_bedsheets_color_and_more'),
  ]

  operations = [
    migrations.AddField(
      model_name='size',
      name='category',
      field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='Категория'),
    ),
  ]
