# Generated by Django 4.0.5 on 2022-07-08 17:27

from django.db import migrations


class Migration(migrations.Migration):

  dependencies = [
    ('api', '0016_size_category'),
  ]

  operations = [
    migrations.RenameField(
      model_name='mattrass',
      old_name='mattras_type',
      new_name='mattrass_type',
    ),
  ]
