# Generated by Django 4.0.5 on 2022-07-10 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

  dependencies = [
    ('api', '0017_rename_mattras_type_mattrass_mattrass_type'),
  ]

  operations = [
    migrations.AlterField(
      model_name='basis',
      name='basis_type',
      field=models.ManyToManyField(related_name='basis_type', to='api.choice'),
    ),
    migrations.AlterField(
      model_name='basis',
      name='name',
      field=models.CharField(max_length=32, unique=True, verbose_name='Название'),
    ),
    migrations.AlterField(
      model_name='bed',
      name='bed_type',
      field=models.ManyToManyField(related_name='bed_type', to='api.choice'),
    ),
    migrations.AlterField(
      model_name='bed',
      name='name',
      field=models.CharField(max_length=32, unique=True, verbose_name='Название'),
    ),
    migrations.AlterField(
      model_name='bedsheets',
      name='bedsheets_color',
      field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bedsheets_color', to='api.choice'),
    ),
    migrations.AlterField(
      model_name='bedsheets',
      name='bedsheets_type',
      field=models.ManyToManyField(related_name='bedsheets_type', to='api.choice'),
    ),
    migrations.AlterField(
      model_name='bedsheets',
      name='name',
      field=models.CharField(max_length=32, unique=True, verbose_name='Название'),
    ),
    migrations.AlterField(
      model_name='bedsheets',
      name='package',
      field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packageBS', to='api.choice'),
    ),
    migrations.AlterField(
      model_name='bedsheets',
      name='tissue',
      field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tissue', to='api.choice'),
    ),
    migrations.AlterField(
      model_name='blanket',
      name='age',
      field=models.ManyToManyField(related_name='ageBl', to='api.choice'),
    ),
    migrations.AlterField(
      model_name='blanket',
      name='blanket_color',
      field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blanket_color', to='api.choice'),
    ),
    migrations.AlterField(
      model_name='blanket',
      name='blanket_type',
      field=models.ManyToManyField(related_name='blanket_type', to='api.choice'),
    ),
    migrations.AlterField(
      model_name='blanket',
      name='filling',
      field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filling', to='api.choice'),
    ),
    migrations.AlterField(
      model_name='blanket',
      name='name',
      field=models.CharField(max_length=32, unique=True, verbose_name='Название'),
    ),
    migrations.AlterField(
      model_name='blanket',
      name='package',
      field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packageBl', to='api.choice'),
    ),
    migrations.AlterField(
      model_name='choice',
      name='name',
      field=models.CharField(choices=[('ОБЩИЕ', 'ОБЩИЕ'), ('age', 'Для возраста'), ('package', 'Упаковка'), ('cover', 'Ткань чехла'), ('', ''), ('Mattrass', 'ТОЛЬКО МАТРАС'), ('mattrass_type', 'Тип матраса'), ('collection', 'Коллекция'), ('construction', 'Конструкция'), ('rigidity', 'Уровень жесткости стороны'), ('springblock', 'Пружинный блок'), ('', ''), ('Pillow', 'ТОЛЬКО ПОДУШКА'), ('material_filler', 'Материал наполнения'), ('', ''), ('MattrassPad', 'ТОЛЬКО НАМАТРАСНИК'), ('mattrasspad_type', 'Тип наматрасника'), ('binding', 'Крепление'), ('', ''), ('Blanket', 'ТОЛЬКО ОДЕЯЛО'), ('blanket_type', 'Тип одеяла'), ('blanket_color', 'Цвет одеяла'), ('filling', 'Наполнитель'), ('', ''), ('BedSheets', 'ТОЛЬКО ПОСТЕЛЬНОЕ БЕЛЬЕ'), ('bedsheets_type', 'Тип комплекта'), ('bedsheets_color', 'Цвет комплекта'), ('tissue', 'Ткань'), ('', ''), ('Bed', 'ТОЛЬКО КРОВАТЬ'), ('bed_type', 'Вид кровати'), ('', ''), ('Stand', 'ТОЛЬКО ТУМБА'), ('material', 'Материал'), ('', ''), ('Basis', 'ТОЛЬКО ОСНОВАНИЕ'), ('basis_type', 'Вид основания')], max_length=32, verbose_name='Характеристика'),
    ),
    migrations.AlterField(
      model_name='choice',
      name='property_ro',
      field=models.CharField(blank=True, max_length=32, verbose_name='Вариант выбора (ro)'),
    ),
    migrations.AlterField(
      model_name='mattrass',
      name='age',
      field=models.ManyToManyField(related_name='ageM', to='api.choice'),
    ),
    migrations.AlterField(
      model_name='mattrass',
      name='collection',
      field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='api.choice'),
    ),
    migrations.AlterField(
      model_name='mattrass',
      name='construction',
      field=models.ManyToManyField(related_name='construction', to='api.choice'),
    ),
    migrations.AlterField(
      model_name='mattrass',
      name='cover',
      field=models.BooleanField(default=True, verbose_name='Съемный чехол'),
    ),
    migrations.AlterField(
      model_name='mattrass',
      name='lifetime',
      field=models.IntegerField(default=10, verbose_name='Срок Службы'),
    ),
    migrations.AlterField(
      model_name='mattrass',
      name='mattrass_type',
      field=models.ManyToManyField(related_name='mattrass_type', to='api.choice'),
    ),
    migrations.AlterField(
      model_name='mattrass',
      name='name',
      field=models.CharField(max_length=32, unique=True, verbose_name='Название'),
    ),
    migrations.AlterField(
      model_name='mattrass',
      name='package',
      field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packageM', to='api.choice'),
    ),
    migrations.AlterField(
      model_name='mattrass',
      name='rigidity1',
      field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rigidity1', to='api.choice'),
    ),
    migrations.AlterField(
      model_name='mattrass',
      name='rigidity2',
      field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rigidity2', to='api.choice'),
    ),
    migrations.AlterField(
      model_name='mattrass',
      name='springblock',
      field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='springblock', to='api.choice'),
    ),
    migrations.AlterField(
      model_name='mattrasspad',
      name='binding',
      field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binding', to='api.choice'),
    ),
    migrations.AlterField(
      model_name='mattrasspad',
      name='cover',
      field=models.ManyToManyField(related_name='coverMP', to='api.choice'),
    ),
    migrations.AlterField(
      model_name='mattrasspad',
      name='mattrasspad_type',
      field=models.ManyToManyField(related_name='mattrasspad_type', to='api.choice'),
    ),
    migrations.AlterField(
      model_name='mattrasspad',
      name='name',
      field=models.CharField(max_length=32, unique=True, verbose_name='Название'),
    ),
    migrations.AlterField(
      model_name='pillow',
      name='age',
      field=models.ManyToManyField(related_name='ageP', to='api.choice'),
    ),
    migrations.AlterField(
      model_name='pillow',
      name='cover',
      field=models.ManyToManyField(related_name='coverP', to='api.choice'),
    ),
    migrations.AlterField(
      model_name='pillow',
      name='material_filler',
      field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_filler', to='api.choice'),
    ),
    migrations.AlterField(
      model_name='pillow',
      name='name',
      field=models.CharField(max_length=32, unique=True, verbose_name='Название'),
    ),
    migrations.AlterField(
      model_name='stand',
      name='material',
      field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material', to='api.choice'),
    ),
    migrations.AlterField(
      model_name='stand',
      name='name',
      field=models.CharField(max_length=32, unique=True, verbose_name='Название'),
    ),
  ]
