# Generated by Django 4.0.5 on 2022-07-16 09:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_basis_basis_type_alter_basis_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/images', verbose_name='Фото товара')),
            ],
            options={
                'verbose_name': 'фотография',
                'verbose_name_plural': 'фотографии',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='media/videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='Видео о товаре')),
            ],
            options={
                'verbose_name': 'видео',
                'verbose_name_plural': 'видео',
            },
        ),
        migrations.AddField(
            model_name='basis',
            name='desc',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='basis',
            name='discount',
            field=models.SmallIntegerField(default=0, verbose_name='Скидка (%)'),
        ),
        migrations.AddField(
            model_name='bed',
            name='desc',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='bed',
            name='discount',
            field=models.SmallIntegerField(default=0, verbose_name='Скидка (%)'),
        ),
        migrations.AddField(
            model_name='bedsheets',
            name='desc',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='bedsheets',
            name='discount',
            field=models.SmallIntegerField(default=0, verbose_name='Скидка (%)'),
        ),
        migrations.AddField(
            model_name='blanket',
            name='desc',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='blanket',
            name='discount',
            field=models.SmallIntegerField(default=0, verbose_name='Скидка (%)'),
        ),
        migrations.AddField(
            model_name='mattrass',
            name='desc',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='mattrass',
            name='discount',
            field=models.SmallIntegerField(default=0, verbose_name='Скидка (%)'),
        ),
        migrations.AddField(
            model_name='mattrasspad',
            name='desc',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='mattrasspad',
            name='discount',
            field=models.SmallIntegerField(default=0, verbose_name='Скидка (%)'),
        ),
        migrations.AddField(
            model_name='pillow',
            name='desc',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='pillow',
            name='discount',
            field=models.SmallIntegerField(default=0, verbose_name='Скидка (%)'),
        ),
        migrations.AddField(
            model_name='stand',
            name='desc',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='stand',
            name='discount',
            field=models.SmallIntegerField(default=0, verbose_name='Скидка (%)'),
        ),
        migrations.AlterField(
            model_name='bedsheets',
            name='bedsheets_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bedsheets_color', to='api.choice'),
        ),
        migrations.AlterField(
            model_name='bedsheets',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packageBS', to='api.choice'),
        ),
        migrations.AlterField(
            model_name='bedsheets',
            name='tissue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tissue', to='api.choice'),
        ),
        migrations.AlterField(
            model_name='blanket',
            name='blanket_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blanket_color', to='api.choice'),
        ),
        migrations.AlterField(
            model_name='blanket',
            name='filling',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filling', to='api.choice'),
        ),
        migrations.AlterField(
            model_name='blanket',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packageBl', to='api.choice'),
        ),
        migrations.AlterField(
            model_name='mattrass',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection', to='api.choice'),
        ),
        migrations.AlterField(
            model_name='mattrass',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packageM', to='api.choice'),
        ),
        migrations.AlterField(
            model_name='mattrass',
            name='rigidity1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rigidity1', to='api.choice'),
        ),
        migrations.AlterField(
            model_name='mattrass',
            name='rigidity2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rigidity2', to='api.choice'),
        ),
        migrations.AlterField(
            model_name='mattrass',
            name='springblock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='springblock', to='api.choice'),
        ),
        migrations.AlterField(
            model_name='mattrasspad',
            name='binding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='binding', to='api.choice'),
        ),
        migrations.AlterField(
            model_name='pillow',
            name='material_filler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_filler', to='api.choice'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material', to='api.choice'),
        ),
        migrations.AddField(
            model_name='basis',
            name='images',
            field=models.ManyToManyField(related_name='images%(class)s', to='api.image', verbose_name='Фотографии товара'),
        ),
        migrations.AddField(
            model_name='basis',
            name='shortcut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.image', verbose_name='Фото на каталог'),
        ),
        migrations.AddField(
            model_name='basis',
            name='videos',
            field=models.ManyToManyField(related_name='videos%(class)s', to='api.image', verbose_name='Видео товара'),
        ),
        migrations.AddField(
            model_name='bed',
            name='images',
            field=models.ManyToManyField(related_name='images%(class)s', to='api.image', verbose_name='Фотографии товара'),
        ),
        migrations.AddField(
            model_name='bed',
            name='shortcut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.image', verbose_name='Фото на каталог'),
        ),
        migrations.AddField(
            model_name='bed',
            name='videos',
            field=models.ManyToManyField(related_name='videos%(class)s', to='api.image', verbose_name='Видео товара'),
        ),
        migrations.AddField(
            model_name='bedsheets',
            name='images',
            field=models.ManyToManyField(related_name='images%(class)s', to='api.image', verbose_name='Фотографии товара'),
        ),
        migrations.AddField(
            model_name='bedsheets',
            name='shortcut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.image', verbose_name='Фото на каталог'),
        ),
        migrations.AddField(
            model_name='bedsheets',
            name='videos',
            field=models.ManyToManyField(related_name='videos%(class)s', to='api.image', verbose_name='Видео товара'),
        ),
        migrations.AddField(
            model_name='blanket',
            name='images',
            field=models.ManyToManyField(related_name='images%(class)s', to='api.image', verbose_name='Фотографии товара'),
        ),
        migrations.AddField(
            model_name='blanket',
            name='shortcut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.image', verbose_name='Фото на каталог'),
        ),
        migrations.AddField(
            model_name='blanket',
            name='videos',
            field=models.ManyToManyField(related_name='videos%(class)s', to='api.image', verbose_name='Видео товара'),
        ),
        migrations.AddField(
            model_name='mattrass',
            name='images',
            field=models.ManyToManyField(related_name='images%(class)s', to='api.image', verbose_name='Фотографии товара'),
        ),
        migrations.AddField(
            model_name='mattrass',
            name='shortcut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.image', verbose_name='Фото на каталог'),
        ),
        migrations.AddField(
            model_name='mattrass',
            name='videos',
            field=models.ManyToManyField(related_name='videos%(class)s', to='api.image', verbose_name='Видео товара'),
        ),
        migrations.AddField(
            model_name='mattrasspad',
            name='images',
            field=models.ManyToManyField(related_name='images%(class)s', to='api.image', verbose_name='Фотографии товара'),
        ),
        migrations.AddField(
            model_name='mattrasspad',
            name='shortcut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.image', verbose_name='Фото на каталог'),
        ),
        migrations.AddField(
            model_name='mattrasspad',
            name='videos',
            field=models.ManyToManyField(related_name='videos%(class)s', to='api.image', verbose_name='Видео товара'),
        ),
        migrations.AddField(
            model_name='pillow',
            name='images',
            field=models.ManyToManyField(related_name='images%(class)s', to='api.image', verbose_name='Фотографии товара'),
        ),
        migrations.AddField(
            model_name='pillow',
            name='shortcut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.image', verbose_name='Фото на каталог'),
        ),
        migrations.AddField(
            model_name='pillow',
            name='videos',
            field=models.ManyToManyField(related_name='videos%(class)s', to='api.image', verbose_name='Видео товара'),
        ),
        migrations.AddField(
            model_name='stand',
            name='images',
            field=models.ManyToManyField(related_name='images%(class)s', to='api.image', verbose_name='Фотографии товара'),
        ),
        migrations.AddField(
            model_name='stand',
            name='shortcut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.image', verbose_name='Фото на каталог'),
        ),
        migrations.AddField(
            model_name='stand',
            name='videos',
            field=models.ManyToManyField(related_name='videos%(class)s', to='api.image', verbose_name='Видео товара'),
        ),
    ]
