# Generated by Django 4.0.5 on 2022-07-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_basis_desc_alter_bed_desc_alter_bedsheets_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desc',
            field=models.TextField(default='', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
