# Generated by Django 4.0.5 on 2022-07-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_category_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en_pl',
            field=models.CharField(default='', max_length=32, verbose_name='Название (en) мн. число'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_en_s',
            field=models.CharField(default='', max_length=32, verbose_name='Название (en) ед. число'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_ro_pl',
            field=models.CharField(default='', max_length=32, verbose_name='Название (ro) мн. число'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_ro_s',
            field=models.CharField(default='', max_length=32, verbose_name='Название (ro) ед. число'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru_pl',
            field=models.CharField(default='', max_length=32, verbose_name='Название (ru) мн. число'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru_s',
            field=models.CharField(default='', max_length=32, verbose_name='Название (ru) ед. число'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='property_en',
            field=models.CharField(blank=True, max_length=32, verbose_name='Вариант выбора (en)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Mattrass', 'Saltea'), ('Pillow', 'Perna'), ('MattrassPad', 'Husa'), ('Blanket', 'Plapuma'), ('BedSheets', 'Lenjerie de Pat'), ('Bed', 'Pat'), ('Stand', 'Noptiera'), ('Basis', 'Somiera')], max_length=32, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='name',
            field=models.CharField(choices=[('ОБЩИЕ', 'ОБЩИЕ'), ('age', 'Для возраста'), ('package', 'Упаковка'), ('cover', 'Ткань чехла'), ('', ''), ('Mattrass', 'ТОЛЬКО SALTEA'), ('mattrass_type', 'Тип матраса'), ('collection', 'Коллекция'), ('construction', 'Конструкция'), ('rigidity', 'Уровень жесткости стороны'), ('springblock', 'Пружинный блок'), ('', ''), ('Pillow', 'ТОЛЬКО PERNA'), ('material_filler', 'Материал наполнения'), ('', ''), ('MattrassPad', 'ТОЛЬКО HUSA'), ('mattrasspad_type', 'Тип наматрасника'), ('binding', 'Крепление'), ('', ''), ('Blanket', 'ТОЛЬКО PLAPUMA'), ('blanket_type', 'Тип одеяла'), ('blanket_color', 'Цвет одеяла'), ('filling', 'Наполнитель'), ('', ''), ('BedSheets', 'ТОЛЬКО LENJERIE DE PAT'), ('bedsheets_type', 'Тип комплекта'), ('bedsheets_color', 'Цвет комплекта'), ('tissue', 'Ткань'), ('', ''), ('Bed', 'ТОЛЬКО PAT'), ('bed_type', 'Вид кровати'), ('', ''), ('Stand', 'ТОЛЬКО NOPTIERA'), ('material', 'Материал'), ('', ''), ('Basis', 'ТОЛЬКО SOMIERA'), ('basis_type', 'Вид основания')], max_length=32, verbose_name='Характеристика'),
        ),
    ]
