# Generated by Django 4.0.5 on 2022-07-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('api', '0023_category_name_en_pl_category_name_en_s_and_more'),
  ]

  operations = [
    migrations.RenameField(
      model_name='category',
      old_name='desc',
      new_name='desc_en',
    ),
    migrations.AddField(
      model_name='category',
      name='desc_ru',
      field=models.TextField(default='', verbose_name='Описание'),
      preserve_default=False,
    ),
    migrations.AlterField(
      model_name='category',
      name='name',
      field=models.CharField(choices=[('Mattrass', 'Матрас'), ('Pillow', 'Подушка'), ('MattrassPad', 'Наматрасник'), ('Blanket', 'Одеяло'), ('BedSheets', 'Постельное белье'), ('Bed', 'Кровать'), ('Stand', 'Тумба'), ('Basis', 'Основание')], max_length=32, unique=True, verbose_name='Название'),
    ),
    migrations.AlterField(
      model_name='choice',
      name='name',
      field=models.CharField(choices=[('ОБЩИЕ', 'ОБЩИЕ'), ('age', 'Для возраста'), ('package', 'Упаковка'), ('cover', 'Ткань чехла'), ('', ''), ('Mattrass', 'ТОЛЬКО МАТРАС'), ('mattrass_type', 'Тип матраса'), ('collection', 'Коллекция'), ('construction', 'Конструкция'), ('rigidity', 'Уровень жесткости стороны'), ('springblock', 'Пружинный блок'), ('', ''), ('Pillow', 'ТОЛЬКО ПОДУШКА'), ('material_filler', 'Материал наполнения'), ('', ''), ('MattrassPad', 'ТОЛЬКО НАМАТРАСНИК'), ('mattrasspad_type', 'Тип наматрасника'), ('binding', 'Крепление'), ('', ''), ('Blanket', 'ТОЛЬКО ОДЕЯЛО'), ('blanket_type', 'Тип одеяла'), ('blanket_color', 'Цвет одеяла'), ('filling', 'Наполнитель'), ('', ''), ('BedSheets', 'ТОЛЬКО ПОСТЕЛЬНОЕ БЕЛЬЕ'), ('bedsheets_type', 'Тип комплекта'), ('bedsheets_color', 'Цвет комплекта'), ('tissue', 'Ткань'), ('', ''), ('Bed', 'ТОЛЬКО КРОВАТЬ'), ('bed_type', 'Вид кровати'), ('', ''), ('Stand', 'ТОЛЬКО ТУМБА'), ('material', 'Материал'), ('', ''), ('Basis', 'ТОЛЬКО ОСНОВАНИЕ'), ('basis_type', 'Вид основания')], max_length=32, verbose_name='Характеристика'),
    ),
  ]
