# Generated by Django 4.0.5 on 2022-07-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_category_desc_ro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desc_en',
            field=models.TextField(verbose_name='Описание (en)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='desc_ro',
            field=models.TextField(verbose_name='Описание (ro)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='desc_ru',
            field=models.TextField(verbose_name='Описание (ru)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en_pl',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en_s',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ro_pl',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ro_s',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru_pl',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru_s',
            field=models.CharField(max_length=32),
        ),
    ]
