# Generated by Django 4.0.5 on 2022-07-22 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_choice_name_stand_pillow_mattresspad_mattress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bedsheets',
            name='package',
        ),
        migrations.RemoveField(
            model_name='blanket',
            name='package',
        ),
        migrations.RemoveField(
            model_name='mattress',
            name='package',
        ),
        migrations.AlterField(
            model_name='category',
            name='desc_en',
            field=models.TextField(blank=True, verbose_name='Описание (en)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='desc_ro',
            field=models.TextField(blank=True, verbose_name='Описание (ro)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='desc_ru',
            field=models.TextField(blank=True, verbose_name='Описание (ru)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Mattress', 'Матрас'), ('Pillow', 'Подушка'), ('MattressPad', 'Наматрасник'), ('Blanket', 'Одеяло'), ('BedSheets', 'Постельное белье'), ('Bed', 'Кровать'), ('Stand', 'Тумба'), ('Basis', 'Основание')], max_length=32, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='name',
            field=models.CharField(choices=[('ОБЩИЕ', 'ОБЩИЕ'), ('age', 'Для возраста'), ('cover', 'Ткань чехла'), ('', ''), ('Mattress', 'ТОЛЬКО МАТРАС'), ('mattress_type', 'Тип матраса'), ('collection', 'Коллекция'), ('construction', 'Конструкция'), ('rigidity', 'Уровень жесткости стороны'), ('springblock', 'Пружинный блок'), ('', ''), ('Pillow', 'ТОЛЬКО ПОДУШКА'), ('material_filler', 'Материал наполнения'), ('', ''), ('MattressPad', 'ТОЛЬКО НАМАТРАСНИК'), ('mattresspad_type', 'Тип наматрасника'), ('binding', 'Крепление'), ('', ''), ('Blanket', 'ТОЛЬКО ОДЕЯЛО'), ('blanket_type', 'Тип одеяла'), ('blanket_color', 'Цвет одеяла'), ('filling', 'Наполнитель'), ('', ''), ('BedSheets', 'ТОЛЬКО ПОСТЕЛЬНОЕ БЕЛЬЕ'), ('bedsheets_type', 'Тип комплекта'), ('bedsheets_color', 'Цвет комплекта'), ('tissue', 'Ткань'), ('', ''), ('Bed', 'ТОЛЬКО КРОВАТЬ'), ('bed_type', 'Вид кровати'), ('', ''), ('Stand', 'ТОЛЬКО ТУМБА'), ('material', 'Материал'), ('', ''), ('Basis', 'ТОЛЬКО ОСНОВАНИЕ'), ('basis_type', 'Вид основания')], max_length=32, verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Фото товара'),
        ),
        migrations.RemoveField(
            model_name='pillow',
            name='material_filler',
        ),
        migrations.AddField(
            model_name='pillow',
            name='material_filler',
            field=models.ManyToManyField(related_name='material_filler', to='api.choice'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='Видео о товаре'),
        ),
    ]
