# Generated by Django 3.1.3 on 2022-08-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('api', '0037_auto_20220802_1550'),
  ]

  operations = [
    migrations.RenameField(
      model_name='mattress',
      old_name='cover',
      new_name='case',
    ),
    migrations.AddField(
      model_name='mattresspad',
      name='case',
      field=models.BooleanField(default=True, verbose_name='Съемный чехол'),
    ),
    migrations.AddField(
      model_name='pillow',
      name='case',
      field=models.BooleanField(default=True, verbose_name='Съемный чехол'),
    ),
    migrations.AlterField(
      model_name='mattress',
      name='structure',
      field=models.ManyToManyField(related_name='structure_mattress', to='api.Layer', verbose_name='Структура'),
    ),
    migrations.AlterField(
      model_name='mattress',
      name='technologies',
      field=models.ManyToManyField(related_name='technologies_mattress', to='api.Technology', verbose_name='Технологии'),
    ),
    migrations.AlterField(
      model_name='mattresspad',
      name='structure',
      field=models.ManyToManyField(related_name='structure_mattresspad', to='api.Layer', verbose_name='Структура'),
    ),
    migrations.AlterField(
      model_name='mattresspad',
      name='technologies',
      field=models.ManyToManyField(related_name='technologies_mattresspad', to='api.Technology', verbose_name='Технологии'),
    ),
    migrations.AlterField(
      model_name='pillow',
      name='structure',
      field=models.ManyToManyField(related_name='structure_pillow', to='api.Layer', verbose_name='Структура'),
    ),
  ]
