# Generated by Django 3.1.3 on 2022-08-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20220804_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='height',
        ),
        migrations.AlterField(
            model_name='basis',
            name='distance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='basis',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='basis',
            name='legs_height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='basis',
            name='width',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='blanket',
            name='density',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mattress',
            name='case',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mattress',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mattress',
            name='lifetime',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='mattress',
            name='max_pressure',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mattress',
            name='springs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mattresspad',
            name='case',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mattresspad',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pillow',
            name='case',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pillow',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stand',
            name='height',
            field=models.IntegerField(),
        ),
    ]
