# Generated by Django 3.1.3 on 2022-08-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20220804_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='headboard_height',
            field=models.IntegerField(default=0),
        ),
    ]
