# Generated by Django 3.1.3 on 2022-08-04 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_bed_headboard_height'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layer',
            options={'verbose_name': 'слой', 'verbose_name_plural': 'слои'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name': 'технология', 'verbose_name_plural': 'технологии'},
        ),
        migrations.AddField(
            model_name='mattresspad',
            name='rigidity1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rigidity1mattresspad', to='api.choice'),
        ),
        migrations.AddField(
            model_name='mattresspad',
            name='rigidity2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rigidity2mattresspad', to='api.choice'),
        ),
        migrations.AlterField(
            model_name='basis',
            name='recomended',
            field=models.ManyToManyField(related_name='recomendedBasis', to='api.Mattress', verbose_name='Рекомендовано для матрассов'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='name',
            field=models.CharField(choices=[('ОБЩИЕ', 'ОБЩИЕ'), ('age', 'Для возраста'), ('rigidity', 'Уровень жесткости стороны'), ('cover', 'Ткань чехла'), ('', ''), ('Mattress', 'ТОЛЬКО МАТРАС'), ('mattress_type', 'Тип матраса'), ('collection', 'Коллекция'), ('construction', 'Конструкция'), ('rigidity', 'Уровень жесткости стороны'), ('springblock', 'Пружинный блок'), ('', ''), ('Pillow', 'ТОЛЬКО ПОДУШКА'), ('material_filler', 'Материал наполнения'), ('', ''), ('MattressPad', 'ТОЛЬКО НАМАТРАСНИК'), ('mattresspad_type', 'Тип наматрасника'), ('rigidity', 'Уровень жесткости стороны'), ('binding', 'Крепление'), ('', ''), ('Blanket', 'ТОЛЬКО ОДЕЯЛО'), ('blanket_type', 'Тип одеяла'), ('blanket_color', 'Цвет одеяла'), ('filling', 'Наполнитель'), ('', ''), ('BedSheets', 'ТОЛЬКО ПОСТЕЛЬНОЕ БЕЛЬЕ'), ('bedsheets_type', 'Тип комплекта'), ('bedsheets_color', 'Цвет комплекта'), ('tissue', 'Ткань'), ('', ''), ('Bed', 'ТОЛЬКО КРОВАТЬ'), ('bed_type', 'Вид кровати'), ('', ''), ('Stand', 'ТОЛЬКО ТУМБА'), ('material', 'Материал'), ('', ''), ('Basis', 'ТОЛЬКО ОСНОВАНИЕ'), ('basis_type', 'Вид основания')], max_length=32, verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='mattress',
            name='rigidity1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rigidity1mattress', to='api.choice'),
        ),
        migrations.AlterField(
            model_name='mattress',
            name='rigidity2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rigidity2mattress', to='api.choice'),
        ),
    ]
