# Generated by Django 3.1.3 on 2022-08-04 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

  dependencies = [
    ('api', '0042_auto_20220804_1352'),
  ]

  operations = [
    migrations.AlterField(
      model_name='size',
      name='category',
      field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
    ),
  ]
