# Generated by Django 3.1.3 on 2022-08-04 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20220804_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerMattress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='LayerMattressPad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.RenameField(
            model_name='technology',
            old_name='desc',
            new_name='desc_en',
        ),
        migrations.RenameField(
            model_name='technology',
            old_name='name',
            new_name='name_ru',
        ),
        migrations.RemoveField(
            model_name='mattress',
            name='structure',
        ),
        migrations.RemoveField(
            model_name='mattresspad',
            name='structure',
        ),
        migrations.AddField(
            model_name='technology',
            name='desc_ro',
            field=models.TextField(default='', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technology',
            name='desc_ru',
            field=models.TextField(default='', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technology',
            name='name_en',
            field=models.CharField(blank=True, max_length=32, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='technology',
            name='name_ro',
            field=models.CharField(blank=True, max_length=32, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='mattress',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='technologies_mattress', to='api.Technology', verbose_name='Технологии'),
        ),
        migrations.AlterField(
            model_name='mattresspad',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='technologies_mattresspad', to='api.Technology', verbose_name='Технологии'),
        ),
        migrations.AlterField(
            model_name='pillow',
            name='structure',
            field=models.ManyToManyField(blank=True, related_name='structure_pillow', to='api.Technology', verbose_name='Структура'),
        ),
        migrations.DeleteModel(
            name='Layer',
        ),
        migrations.AddField(
            model_name='layermattresspad',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mattresspad'),
        ),
        migrations.AddField(
            model_name='layermattresspad',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.technology'),
        ),
        migrations.AddField(
            model_name='layermattress',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mattress'),
        ),
        migrations.AddField(
            model_name='layermattress',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.technology'),
        ),
    ]
