# Generated by Django 3.1.3 on 2022-08-20 07:48

from django.db import migrations


class Migration(migrations.Migration):

  dependencies = [
    ('api', '0050_auto_20220820_1040'),
  ]

  operations = [
    migrations.RenameField(
      model_name='marker',
      old_name='name_ru',
      new_name='name',
    ),
    migrations.RemoveField(
      model_name='marker',
      name='name_en',
    ),
    migrations.RemoveField(
      model_name='marker',
      name='name_ro',
    ),
  ]
