# Generated by Django 3.1.3 on 2022-08-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('api', '0061_auto_20220825_2115'),
  ]

  operations = [
    migrations.AlterField(
      model_name='choice',
      name='category',
      field=models.ManyToManyField(related_name='categoryC', to='api.Category'),
    ),
  ]
