# Generated by Django 3.1.3 on 2022-08-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_auto_20220825_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basis',
            name='distance',
            field=models.IntegerField(default=45),
        ),
        migrations.AlterField(
            model_name='basis',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='basis',
            name='legs_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='basis',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blanket',
            name='density',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mattress',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mattress',
            name='max_pressure',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mattresspad',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pillow',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='size',
            name='length',
            field=models.SmallIntegerField(default=200, verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='size',
            name='width',
            field=models.SmallIntegerField(default=80, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='height',
            field=models.IntegerField(default=0),
        ),
    ]
