# Generated by Django 3.1.3 on 2022-08-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_auto_20220830_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedsheetssize',
            name='pillowcase_sizes',
            field=models.ManyToManyField(related_name='pillowcase_sizesbedsheetssize', to='api.Size', verbose_name='Наволочки'),
        ),
        migrations.AlterField(
            model_name='size',
            name='priceEUR',
            field=models.SmallIntegerField(default=0, verbose_name='Цена (евро)'),
        ),
        migrations.AlterField(
            model_name='size',
            name='priceMDL',
            field=models.SmallIntegerField(default=0, verbose_name='Цена (леи)'),
        ),
    ]
