# Generated by Django 3.1.3 on 2022-09-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_auto_20220903_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bedsheets',
            name='name',
        ),
        migrations.AddField(
            model_name='bedsheets',
            name='name_en',
            field=models.CharField(default='', max_length=32, verbose_name='Название (en)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bedsheets',
            name='name_ro',
            field=models.CharField(default='', max_length=32, verbose_name='Название (ro)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bedsheets',
            name='name_ru',
            field=models.CharField(default='', max_length=32, verbose_name='Название (ru)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='name',
            field=models.CharField(choices=[('ОБЩИЕ', 'ОБЩИЕ'), ('age', 'Для возраста'), ('rigidity', 'Уровень жесткости стороны'), ('cover', 'Ткань чехла'), ('', ''), ('Mattress', 'ТОЛЬКО МАТРАС'), ('mattress_type', 'Тип матраса'), ('collection', 'Коллекция'), ('construction', 'Конструкция'), ('rigidity', 'Уровень жесткости стороны'), ('springblock', 'Пружинный блок'), ('', ''), ('Pillow', 'ТОЛЬКО ПОДУШКА'), ('material_filler', 'Материал наполнения'), ('', ''), ('MattressPad', 'ТОЛЬКО НАМАТРАСНИК'), ('mattresspad_type', 'Тип наматрасника'), ('rigidity', 'Уровень жесткости стороны'), ('binding', 'Крепление'), ('', ''), ('Blanket', 'ТОЛЬКО ОДЕЯЛО'), ('blanket_type', 'Тип одеяла'), ('blanket_color', 'Цвет одеяла'), ('filling', 'Наполнитель'), ('', ''), ('BedSheets', 'ТОЛЬКО КОМПЛЕКТ ПОСТЕЛЬНОГО БЕЛЬЯ'), ('bedsheets_type', 'Тип комплекта'), ('bedsheets_color', 'Цвет комплекта'), ('tissue', 'Ткань'), ('', ''), ('Bed', 'ТОЛЬКО КРОВАТЬ'), ('bed_type', 'Вид кровати'), ('', ''), ('Stand', 'ТОЛЬКО ТУМБА'), ('material', 'Материал'), ('', ''), ('Basis', 'ТОЛЬКО ОСНОВАНИЕ')], max_length=32, verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='products', verbose_name='Фото товара'),
        ),
    ]
