# Generated by Django 3.1.3 on 2022-09-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_auto_20220904_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='name_ru',
            field=models.CharField(max_length=32, unique=True, verbose_name='Название (ru)'),
        ),
    ]
