# Generated by Django 3.1.3 on 2022-09-05 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_auto_20220904_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='desc_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='desc_ro',
        ),
        migrations.RemoveField(
            model_name='category',
            name='desc_ru',
        ),
    ]
