# Generated by Django 4.1.1 on 2022-10-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('api', '0077_alter_size_category'),
  ]

  operations = [
    migrations.AddField(
      model_name='size',
      name='is_sailng',
      field=models.BooleanField(default=False, verbose_name='На распродаже'),
    ),
  ]
