# Generated by Django 4.1.1 on 2022-10-22 07:56

from django.db import migrations


class Migration(migrations.Migration):

  dependencies = [
    ('api', '0078_size_is_sailng'),
  ]

  operations = [
    migrations.RenameField(
      model_name='size',
      old_name='is_sailng',
      new_name='on_sale',
    ),
  ]
