# Generated by Django 4.1.1 on 2022-10-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('api', '0080_stock'),
  ]

  operations = [
    migrations.AlterModelOptions(
      name='stock',
      options={'verbose_name': 'размер', 'verbose_name_plural': 'размеры'},
    ),
    migrations.RenameField(
      model_name='stock',
      old_name='collection',
      new_name='collections',
    ),
    migrations.AlterField(
      model_name='stock',
      name='sizes',
      field=models.ManyToManyField(blank=True, related_name='sizes_stock', to='api.size', verbose_name='Размеры'),
    ),
  ]
