# Generated by Django 4.1.2 on 2022-10-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0081_alter_stock_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stock",
            options={"verbose_name": "акция", "verbose_name_plural": "акции"},
        ),
    ]
