# Generated by Django 4.1.2 on 2022-12-11 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0082_alter_stock_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="size",
            name="priceMDL",
        ),
    ]
