# Generated by Django 5.0.1 on 2024-04-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_category_desc_en_category_desc_ro_category_desc_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desc_en',
            field=models.TextField(blank=True, verbose_name='Описание (en)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='desc_ro',
            field=models.TextField(blank=True, verbose_name='Описание (ro)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='desc_ru',
            field=models.TextField(blank=True, verbose_name='Описание (ru)'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='name',
            field=models.CharField(choices=[('ОБЩИЕ', 'ОБЩИЕ'), ('age', 'Для возраста'), ('rigidity', 'Уровень жесткости стороны'), ('cover', 'Ткань чехла'), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('Basis', 'ТОЛЬКО ОСНОВАНИЕ')], max_length=32, verbose_name='Характеристика'),
        ),
    ]
