# Generated by Django 5.0.1 on 2024-05-05 19:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_alter_category_desc_en_alter_category_desc_ro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='name',
            field=models.CharField(choices=[('ОБЩИЕ', 'ОБЩИЕ'), ('age', 'Для возраста'), ('rigidity', 'Уровень жесткости стороны'), ('cover', 'Ткань чехла'), ('', ''), ('Mattress', 'ТОЛЬКО МАТРАС'), ('mattress_type', 'Тип матраса'), ('collection', 'Коллекция'), ('construction', 'Конструкция'), ('rigidity', 'Уровень жесткости стороны'), ('springblock', 'Пружинный блок'), ('', ''), ('Pillow', 'ТОЛЬКО ПОДУШКА'), ('material_filler', 'Материал наполнения'), ('', ''), ('MattressPad', 'ТОЛЬКО НАМАТРАСНИК'), ('mattresspad_type', 'Тип наматрасника'), ('rigidity', 'Уровень жесткости стороны'), ('binding', 'Крепление'), ('', ''), ('Blanket', 'ТОЛЬКО ОДЕЯЛО'), ('blanket_type', 'Тип одеяла'), ('blanket_color', 'Цвет одеяла'), ('filling', 'Наполнитель'), ('', ''), ('BedSheets', 'ТОЛЬКО КОМПЛЕКТ ПОСТЕЛЬНОГО БЕЛЬЯ'), ('bedsheets_type', 'Тип комплекта'), ('bedsheets_color', 'Цвет комплекта'), ('tissue', 'Ткань'), ('', ''), ('Bed', 'ТОЛЬКО КРОВАТЬ'), ('bed_type', 'Вид кровати'), ('', ''), ('Stand', 'ТОЛЬКО ТУМБА'), ('material', 'Материал'), ('', ''), ('Basis', 'ТОЛЬКО ОСНОВАНИЕ')], max_length=32, verbose_name='Характеристика'),
        ),
        migrations.CreateModel(
            name='Stockable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.size', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'модель',
                'verbose_name_plural': 'модели',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('A', 'Добавить в систему'), ('O', 'Пометить как бронь'), ('C', 'Отменить бронь'), ('S', 'Отметить как проданный'), ('T', 'Переместить')], max_length=1, verbose_name='Тип действия')),
                ('person', models.CharField(max_length=2, verbose_name='Деятель')),
                ('place', models.CharField(choices=[('SN', 'Новый склад'), ('SO', 'Старый склад'), ('JU', 'Джамбо'), ('CI', 'Чеканы'), ('RI', 'Рышкановка'), ('D1', 'Игорь'), ('D2', 'Оргеев'), ('D3', 'Унгены'), ('CA', 'Машина')], max_length=2, verbose_name='Место товара')),
                ('date', models.DateField(default=datetime.datetime(2024, 5, 5, 22, 11, 9, 74087), verbose_name='Дата')),
                ('stockable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='api.stockable', verbose_name='Модель')),
            ],
        ),
    ]
