# Generated by Django 5.0.1 on 2024-05-05 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_alter_choice_name_stockable_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'действие', 'verbose_name_plural': 'действия'},
        ),
        migrations.AddField(
            model_name='bedsheetssize',
            name='duvet_cover_size_1',
            field=models.CharField(default='', max_length=7, verbose_name='Размер Пододеяльника'),
        ),
        migrations.AddField(
            model_name='bedsheetssize',
            name='elasticated_sheet_size_1',
            field=models.CharField(default='', max_length=7, verbose_name='Простыня на резинке'),
        ),
        migrations.AddField(
            model_name='bedsheetssize',
            name='pillowcase_sizes_1',
            field=models.CharField(default='', max_length=11, verbose_name='Наволочки'),
        ),
        migrations.AddField(
            model_name='bedsheetssize',
            name='sheet_size_1',
            field=models.CharField(default='', max_length=7, verbose_name='Простыня'),
        ),
        migrations.AlterField(
            model_name='action',
            name='date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.CharField(choices=[('A', 'Добавить в систему'), ('O', 'Пометить как бронь'), ('C', 'Отменить бронь'), ('S', 'Отметить как проданный'), ('T', 'Переместить')], default='A', max_length=1, verbose_name='Тип действия'),
        ),
    ]
