# Generated by Django 5.0.1 on 2024-05-05 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_alter_action_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bedsheetssize',
            name='duvet_cover_size',
        ),
        migrations.RemoveField(
            model_name='bedsheetssize',
            name='elasticated_sheet_size',
        ),
        migrations.RemoveField(
            model_name='bedsheetssize',
            name='pillowcase_sizes',
        ),
        migrations.RemoveField(
            model_name='bedsheetssize',
            name='sheet_size',
        ),
    ]
