# Generated by Django 5.0.1 on 2024-05-05 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_remove_bedsheetssize_duvet_cover_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bedsheetssize',
            old_name='duvet_cover_size_1',
            new_name='duvet_cover_size',
        ),
        migrations.RenameField(
            model_name='bedsheetssize',
            old_name='elasticated_sheet_size_1',
            new_name='elasticated_sheet_size',
        ),
        migrations.RenameField(
            model_name='bedsheetssize',
            old_name='pillowcase_sizes_1',
            new_name='pillowcase_sizes',
        ),
        migrations.RenameField(
            model_name='bedsheetssize',
            old_name='sheet_size_1',
            new_name='sheet_size',
        ),
    ]
