# Generated by Django 5.0.1 on 2024-05-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_rename_duvet_cover_size_1_bedsheetssize_duvet_cover_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedsheetssize',
            name='duvet_cover_size',
            field=models.CharField(max_length=7, verbose_name='Размер Пододеяльника'),
        ),
        migrations.AlterField(
            model_name='bedsheetssize',
            name='elasticated_sheet_size',
            field=models.CharField(max_length=7, verbose_name='Простыня на резинке'),
        ),
        migrations.AlterField(
            model_name='bedsheetssize',
            name='pillowcase_sizes',
            field=models.CharField(max_length=11, verbose_name='Наволочки'),
        ),
        migrations.AlterField(
            model_name='bedsheetssize',
            name='sheet_size',
            field=models.CharField(max_length=7, verbose_name='Простыня'),
        ),
    ]
