# Generated by Django 5.0.1 on 2024-05-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_alter_bedsheetssize_duvet_cover_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockable',
            name='product',
            field=models.CharField(default='', max_length=32, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.CharField(choices=[('A', 'Добавить в систему'), ('O', 'Пометить как бронь'), ('C', 'Отменить бронь'), ('S', 'Отметить как проданный'), ('R', 'Получить возврат'), ('T', 'Переместить')], default='A', max_length=1, verbose_name='Тип действия'),
        ),
        migrations.AlterField(
            model_name='stockable',
            name='size',
            field=models.CharField(default='', max_length=7, verbose_name='Размер'),
        ),
    ]
