# Generated by Django 5.0.1 on 2024-05-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_stockable_product_alter_action_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockable',
            name='product',
            field=models.CharField(max_length=32, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='stockable',
            name='size',
            field=models.CharField(max_length=7, verbose_name='Размер'),
        ),
    ]
