# Generated by Django 5.0.1 on 2024-05-07 16:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_alter_stockable_product_alter_stockable_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'таблица',
                'verbose_name_plural': 'таблицы',
            },
        ),
        migrations.AddField(
            model_name='stockable',
            name='table',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stockables', to='api.table'),
        ),
    ]
