# Generated by Django 5.0.1 on 2024-05-07 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_table_stockable_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='date',
        ),
        migrations.AddField(
            model_name='table',
            name='month',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Месяц'),
        ),
        migrations.AddField(
            model_name='table',
            name='year',
            field=models.PositiveSmallIntegerField(default=2024, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='stockable',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockables', to='api.table'),
        ),
    ]
