# Generated by Django 5.0.1 on 2024-05-09 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_remove_table_date_table_month_table_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockable',
            name='table',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='Stockable',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
