# Generated by Django 5.1.6 on 2025-05-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_squashed_0118_size_out_of_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristictype',
            name='data_type',
            field=models.CharField(choices=[('B', 'булеан'), ('I', 'целое число'), ('S', 'строка')], max_length=1, verbose_name='Тип данных'),
        ),
    ]
