# Generated by Django 5.2.8 on 2025-11-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_alter_characteristictype_data_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booleancharacteristic',
            options={'ordering': ['type', 'product', 'value'], 'verbose_name': 'Характиристика (булеан)', 'verbose_name_plural': 'Характеристики (булеан)'},
        ),
        migrations.AlterModelOptions(
            name='integercharacteristic',
            options={'ordering': ['type', 'product', 'value'], 'verbose_name': 'Характиристика (целое число)', 'verbose_name_plural': 'Характеристики (целые числа)'},
        ),
        migrations.AlterModelOptions(
            name='stringcharacteristic',
            options={'ordering': ['type', 'product', 'value_ru'], 'verbose_name': 'Характиристика (строка)', 'verbose_name_plural': 'Характеристики (строки)'},
        ),
        migrations.AddField(
            model_name='product',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='Отключен'),
        ),
        migrations.AddField(
            model_name='size',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='Отключен'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc_en',
            field=models.TextField(blank=True, verbose_name='Описание (en)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc_ro',
            field=models.TextField(blank=True, verbose_name='Описание (ro)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc_ru',
            field=models.TextField(blank=True, verbose_name='Описание (ru)'),
        ),
        migrations.AlterField(
            model_name='size',
            name='out_of_stock',
            field=models.BooleanField(default=False, verbose_name='Отсуствует'),
        ),
    ]
