from .search import SearchView
from .best import BestView
from .mattress_collections_price import MattressCollectionsPriceView
from .category import CategoryView
from .listed_products import ListedProductsView
from .detailed_product import DetailedProductView
from .sales import SalesView
from .stock import StockView
from .worker import WorkerView