# Generated by Django 3.1.3 on 2022-03-27 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Товар', models.CharField(choices=[('Mattrass', 'Матрас'), ('Pillow', 'Подушки')], max_length=20)),
                ('Вид', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mattrass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vegas_api.type')),
            ],
        ),
    ]
