# Generated by Django 3.1.3 on 2022-03-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegas_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mattrass',
            options={'verbose_name': 'mattrass', 'verbose_name_plural': 'mattrasses'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'type', 'verbose_name_plural': 'types'},
        ),
        migrations.AlterField(
            model_name='type',
            name='Товар',
            field=models.CharField(choices=[('Mattrass', 'Матрас'), ('Pillow', 'Подушка')], max_length=20),
        ),
    ]
