# Generated by Django 3.1.3 on 2022-03-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegas_api', '0002_auto_20220327_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='Вид',
        ),
        migrations.RemoveField(
            model_name='type',
            name='Товар',
        ),
        migrations.AddField(
            model_name='type',
            name='product',
            field=models.CharField(choices=[('Mattrass', 'Матрас'), ('Pillow', 'Подушка')], default='lol', max_length=20, verbose_name='Товар'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type',
            name='type',
            field=models.CharField(default='lol', max_length=255, verbose_name='Вид'),
            preserve_default=False,
        ),
    ]
