# Generated by Django 3.1.3 on 2022-03-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegas_api', '0003_auto_20220327_1813'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mattrass',
        ),
    ]
