# Generated by Django 3.1.3 on 2022-03-27 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vegas_api', '0004_delete_mattrass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mattrass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grown_up', models.BooleanField(default=True, verbose_name='Для взрослых')),
                ('garanty', models.IntegerField(verbose_name='Гарантийный срок')),
                ('height', models.IntegerField(verbose_name='Высота')),
                ('max_pressure', models.IntegerField(verbose_name='Макс. нагрузка')),
                ('rigidity1', models.CharField(choices=[('middlehard', 'среднежесткий'), ('average', 'средний')], max_length=30, verbose_name='Уровень жесткости стороны 1')),
                ('rigidity2', models.CharField(choices=[('middlehard', 'среднежесткий'), ('average', 'средний')], max_length=30, verbose_name='Уровень жесткости стороны 2')),
                ('springs', models.IntegerField(verbose_name='Пружины')),
                ('lifetime', models.IntegerField(verbose_name='Срок Службы')),
                ('collection', models.CharField(choices=[('Comfort', 'Comfort'), ('Modern', 'Modern')], max_length=30, verbose_name='Коллекция')),
                ('cover', models.BooleanField(verbose_name='Съемный чехол')),
                ('country', models.CharField(choices=[('Belarus', 'Беларусь')], max_length=30, verbose_name='Коллекция')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vegas_api.type')),
            ],
            options={
                'verbose_name': 'mattrass',
                'verbose_name_plural': 'mattrasses',
            },
        ),
    ]
