# Generated by Django 3.1.3 on 2022-03-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegas_api', '0005_mattrass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mattrass',
            name='country',
            field=models.CharField(choices=[('Belarus', 'Беларусь')], max_length=30, verbose_name='Страна производства'),
        ),
    ]
